# Generated by Django 5.0 on 2024-01-27 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_type_product_type_zapchast'),
    ]

    operations = [
        migrations.CreateModel(
            name='list_type_zapchast_type_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kol_vo', models.IntegerField()),
                ('type_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.type_product')),
                ('type_zapchast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.type_zapchast')),
            ],
        ),
        migrations.AddField(
            model_name='type_product',
            name='type_zapchast',
            field=models.ManyToManyField(through='posts.list_type_zapchast_type_product', to='posts.type_zapchast'),
        ),
    ]
