# Generated by Django 5.0 on 2024-01-27 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_list_type_zapchast_type_product_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='list_type_zapchast_type_product',
            new_name='ListTypeZapchastTypeProduct',
        ),
        migrations.RenameModel(
            old_name='type_zapchast',
            new_name='TypeZapchast',
        ),
        migrations.CreateModel(
            name='TypeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('type_zapchast', models.ManyToManyField(through='posts.ListTypeZapchastTypeProduct', to='posts.typezapchast')),
            ],
        ),
        migrations.AlterField(
            model_name='listtypezapchasttypeproduct',
            name='type_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.typeproduct'),
        ),
        migrations.DeleteModel(
            name='type_product',
        ),
    ]
