# Generated by Django 5.0 on 2024-01-29 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_type_stage_remove_typeproduct_type_zapchast_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partsbytype',
            name='list_parts_by_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stage',
        ),
        migrations.RemoveField(
            model_name='product',
            name='type',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='type',
        ),
        migrations.CreateModel(
            name='SetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kol_vo', models.PositiveIntegerField()),
                ('part_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='part_id', to='posts.type')),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='type_id', to='posts.type')),
            ],
            options={
                'unique_together': {('type_id', 'part_id')},
            },
        ),
        migrations.DeleteModel(
            name='Actions',
        ),
        migrations.DeleteModel(
            name='PartsByType',
        ),
        migrations.DeleteModel(
            name='Stage',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Storage',
        ),
    ]
