# Generated by Django 5.0.3 on 2024-04-06 17:32

import django_matplotlib.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('figure', django_matplotlib.fields.MatplotlibFigureField()),
            ],
        ),
    ]
