# Generated by Django 5.0.3 on 2024-04-09 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graf_matplotlib_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymodel',
            name='figure',
        ),
        migrations.AddField(
            model_name='mymodel',
            name='name_student',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mymodel',
            name='ocenka',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
